version: '3'

services:
  workspace:
    build: dockerfiles/workspace
    container_name: workspace
    tty: true
    environment:
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      DB_HOSTNAME: "app_db"
      DB_PORT: "3306"
      DB_DATABASE: "dev"

  app_db:
    image: mysql:5.7
    container_name: app_db
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3310:3306"
    volumes:
      - ./config/app_db/init:/docker-entrypoint-initdb.d
    expose:
      - 3306

  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - ./data/jenkins:/var/jenkins_home

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
    links:
      - sonarqube_db
    volumes:
      - ./data/sonarqube

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./data/sonarqube

  sonarqube_datastore:
    build: dockerfiles/sonarqube_datastore
    container_name: sonarqube_datastore

  redmine:
    image: redmine
    container_name: redmine
    ports:
      - 3000:3000
    environment:
      REDMINE_DB_MYSQL: redmine_db
      REDMINE_DB_PASSWORD: redmine
    depends_on:
      - redmine_db
    restart: always

  redmine_db:
    image: mariadb
    container_name: redmine_db
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    restart: always

  zabbix_db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  zabbix_server:
    image: zabbix/zabbix-server-mysql
    environment:
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ZBX_DEBUGLEVEL=${LOG_LEVEL}
    ports:
      - "10051:10051"
    links:
      - zabbix_db

  zabbix_web:
    image: zabbix/zabbix-web-apache-mysql
    environment:
      - ZBX_SERVER_HOST=zabbix_server
      - DB_SERVER_HOST=zabbix_db
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PHP_TZ=${TIME_ZONE}
    ports:
      - ${HTTP_PORT}:80
    links:
      - zabbix_server
      - zabbix_db

  zabbix_agent:
    image: zabbix/zabbix-agent
    privileged: true
    environment:
      - ZBX_SERVER_HOST=zabbix_server
    expose:
      - "10050"
    links:
      - zabbix_server
